#!/usr/bin/env bash

display_usage() {
	echo 'pforward forwards a port over SSM, providing functionality similar to the -D flag for ssh.
Usage: pforward <destination> [options...]
Destination: Either a hostname (server.env) or an instance-id

Required Arguments:
 -r, --remote       Remote port
 -l, --local        Local port

Optional Arguments:
 -p, --profile      AWS Profile (default)
 -h, --help         Displays this help text'
}

AWS_PROFILE='default'

params=( $@ )
INPUT="$1"

# parse args
i=0
for arg in "${params[@]}"; do
	if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
		display_usage
		exit 0
	fi
	if [[ "$arg" == "-r" || "$arg" == "--remote" ]]; then
		remoteport="${params[$i+1]}"
	fi
	if [[ "$arg" == "-l" || "$arg" == "--local" ]]; then
		localport="${params[$i+1]}"
	fi
	if [[ "$arg" == "-p" || "$arg" == "--profile" ]]; then
		AWS_PROFILE="${params[$i+1]}"
	fi
	((i++))
done

# check required args were provided
insufficient_args=0
if [[ -z "$INPUT" ]]; then
	echo 'ERROR: No server specified, please specify a server to connect to!' 1>&2
	insufficient_args=1
fi
if [[ -z "$remoteport" ]]; then
	echo 'ERROR: No remote port specified, please specify a remote port with -r' 1>&2
	insufficient_args=1
fi
if [[ -z "$localport" ]]; then
	echo 'ERROR: No local port specified, please specify a local port with -l' 1>&2
	insufficient_args=1
fi
if (( $insufficient_args == 1 )); then
	display_usage
	exit 1
fi

resolve_hostname() {
	local host
	host="$1"
	if [[ -z "$host" ]]; then
		return 1
	fi
	echo "$(aws route53 list-resource-record-sets --hosted-zone-id $HOSTED_ZONE_ID --query 'ResourceRecordSets[?Name == `'$host'.`].ResourceRecords[].Value' --profile $AWS_PROFILE --output text 2> /dev/null | head -n 1)"
}

instance_id_pattern='^m?i-[[:xdigit:]]+$'
if [[ $INPUT =~ $instance_id_pattern ]]; then
	INSTANCE_ID="$INPUT"
else
	HOSTNAME="$INPUT"
	SERVER="${INPUT%%.*}"
	DOMAIN="${INPUT#*.}"

	ZONE_PATH="$(aws route53 list-hosted-zones --query 'HostedZones[?Name ==`'$DOMAIN'.`].Id' --profile $AWS_PROFILE --output text 2> /dev/null)"
	if (( $? != 0 )); then
		echo -e "You don't appear to have the correct permissions. \nPlease ensure the AWS profile that you're using has the correct Route 53 permissions."
		exit 1
	fi

	HOSTED_ZONE_ID="${ZONE_PATH##*/}"
	if [[ "$HOSTED_ZONE_ID" == "null" || -z "$HOSTED_ZONE_ID" ]]; then
		echo "$DOMAIN doesn't appear to be Route 53 Private Hosted Zone in your account. Please double check the domain."
		exit 1
	fi

	ip_address_pattern='^([0-9]+(\.|$)){4}'
	for (( i = 0; i < 10; i++ )); do
		HOSTNAME="$(resolve_hostname $HOSTNAME)"
		if [[ $HOSTNAME =~ $ip_address_pattern ]]; then
			PRIVATE_IP="$HOSTNAME"
			break
		fi
	done
	if (( i == 10 )); then
		#dns recursed too far and we didn't get an ip
		echo "The hostname '$REMAINING_INPUT' couldn't be resolved to an IP."
		exit 1
	fi

	INSTANCE_ID="$(aws ec2 describe-instances --profile $AWS_PROFILE --filters 'Name=private-ip-address,Values='$PRIVATE_IP'' --query 'Reservations[].Instances[0].InstanceId' --output text 2> /dev/null)"

	if [[ -z "$INSTANCE_ID" ]]; then
		echo -e "The domain name provided doesn't exist. Please double check the name and try again.\nOR Ensure the the route 53 entry contains a PRIVATE ip address."
		exit 1
	fi
	if [[ ! "$INSTANCE_ID" =~ $instance_id_pattern ]]; then
		echo "Retrieved instance id $INSTANCE_ID does not seem valid!"
		exit 1
	fi

	echo "[INFO] Found Private IP for $INSTANCE_ID: $PRIVATE_IP"
fi

aws ssm start-session --target "$INSTANCE_ID" --document-name AWS-StartPortForwardingSession --parameters "portNumber"=["$remoteport"],"localPortNumber"=["$localport"]
if (( $? != 0 )); then
	echo 'Connection error!'
	exit 1
else
	echo 'Connection closed.'
fi
